version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: txn_db       
      MYSQL_USER: admin            
      MYSQL_PASSWORD: admin123     
    ports:
      - "3306:3306"  
    volumes:
      - ./data:/var/lib/mysql  